# Generated by Django 3.1.7 on 2021-02-22 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField()),
            ],
        ),
        # migrations.CreateModel(
        #     name='MemberPoint',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('point', models.FloatField()),
        #     ],
        # ),
        migrations.CreateModel(
            name='Supermarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount', models.FloatField()),
                ('new_price', models.FloatField()),
                ('old_price', models.FloatField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.card')),
                ('extra_discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.extradiscount')),
                ('supermarket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.supermarket')),
            ],
        ),
        migrations.CreateModel(
            name='AuthUserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
