# Generated by Django 3.1.7 on 2021-04-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_memberpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
