# Generated by Django 3.1.7 on 2021-04-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_card_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpoint',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
