# Generated by Django 3.1.7 on 2021-04-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0006_contactpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactpost',
            old_name='create_time',
            new_name='time',
        ),
    ]
