# Generated by Django 3.1.7 on 2021-04-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0007_auto_20210414_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpost',
            name='content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactpost',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
